service: participants-express-api

custom:
  tableName: 'participants-table-express-${self:provider.stage}'
  dynamodb:
    start:
      migrate: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["ParticiantsDynamoDBTable", "Arn" ] }
  environment:
    PARTICIPANTS_TABLE: ${self:custom.tableName}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

  createParticipant:
    handler: index.handler
    events:
      - http: 'POST /api/participants'
      
  getParticipants:
    handler: index.handler
    events:
      - http: 
          method: get
          path: api/participants
          cors: true    # This doesn't seem to work in current case 
                        # (maybe because express server?)
                        # Maybe this does the API Gateway cors settings
                        # See https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/serverless.yml.md

  getParticipant:
    handler: index.handler
    events:
      - http: 'GET /api/participants/{proxy+}'

  updateParticipant:
    handler: index.handler
    events:
      - http: 'PUT /api/participants/{proxy+}'

  deleteParticipant:
    handler: index.handler
    events:
      - http: 'DELETE /api/participants/{proxy+}'

resources:
  Resources:
    ParticiantsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: _id
            AttributeType: S
        KeySchema:
          -
            AttributeName: _id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}

plugins:
  - serverless-dynamodb-local
  - serverless-offline #serverless-offline needs to be last in the list